### ISSUE TITLE
[Local Proview] [Moodle] Implement all configurations for secure browser

### ISSUE THREAD

**Issue by devang1281** [talview/moodle-local_proview#101]
User story: https://www.notion.so/talview/Secure-browser-configurations-for-moodle-quiz-479e3417623045b2bbab8cbf79ce03c8?pvs=4
**Is your feature request related to a problem? Please describe.**
A user should be able to implement all possible configurations of secure browser:
- [x] Blacklisted Apps (windows and mac)
- [x] Kiosk mode
- [x] Content Protection

**Describe the solution you'd like**
- While calling the wrapper link for Secure Browser send all the configurations from DB via API
- While Loading CDN add all the parameters from DB to CDN

**Comment by Anil-R07** [comment]
@rohansharmasitoula Tested this ticket along with the ticket https://github.com/talview/moodle-quizaccess_proctor/issues/50
working as expected 
Tested for both proctored and non proctored sessions 
for non proctored it will generate a wrapper link https://pages.talview.com/proview/wrapper/launch-eu/?verificationCode=1730873694925-8040
