### ISSUE TITLE
The plugin's JavaScript leaks the quiz password to the page source code

### ISSUE THREAD

**Issue by mudrd8mz** [talview/moodle-local_proview#24]
The quiz password is supposed to be evaluated server side. Your plugin is sending it to the client. This can have serious impact on the quiz security and reliability.

**Comment by mudrd8mz** [comment]
Why is the quiz password needed in the first place?

**Comment by devang1281** [comment]
The quiz password is removed from the query string and is now being passed internally.

The quiz password is required so that candidate may not access the quiz without proctoring. Candidate will not know the password, it will be automatically injected if proctoring is loading or disabled.
