### ISSUE TITLE
TSB not working properly with password enabled quizzes

### ISSUE THREAD

**Issue by devang1281** [talview/moodle-local_proview#53]
## Description

**Current behavior**
When a quiz is password protected and TSB is enabled, first Proview is launched then the download page for TSB becomes available.

**Expected behavior**
When a quiz is  password protected and TSB is enabled, first TSB download page should be available and when the candidate joins the exam from TSB, Proview should launch.

## Steps to reproduce
1. Create a password-protected quiz on Moodle
2. Enable any type of proctoring for the quiz
3. Enable TSB
4. Take the exam as a candidate

https://github.com/talview/moodle-local_proview/assets/59830586/03f87f5b-9d96-48ad-a90e-920a7a2ffa6c

## Versions

- Moodle: 3.9
- Plugin: 3.1.0
- Browser: Chrome 116.0.5845.96
- OS: macOS Monterey

**Comment by Anil-R07** [comment]
@rohansharmasitoula Tested on Moodle lms 4 version, working as expected 

If the quiz is password protected then when the candidate click on start attempt, then te candidate has to enter the password to start the assessment then if the password is correct the quiz will open on TSB

**Comment by Anil-R07** [comment]
@rohansharmasitoula Observation 2 is working fine after the init script URL Change
