### ISSUE TITLE
To provide ReSync to those who have access to test takers attempt data.

### ISSUE THREAD

**Issue by rakeshprabhu** [talview/moodle-local_proview#61]
If real-time data sync is failed then don't block the test takers. Alternatively, provide the option to resync that data via API to those who have access to students' quiz attempt data. If data not identified then store the information to show "No Data".

**Comment by rohansharmasitoula** [comment]
@rakeshprabhu closing this. The its being tracked by https://github.com/talview/moodle-local_proview/issues/69
