### ISSUE TITLE
Proview video stream is stoped/blocked when used along with Moodle Adaptable theme

### ISSUE THREAD

**Issue by rakeshprabhu** [talview/moodle-local_proview#79]
## Description

**Current behavior**
When the test taker completes the Proview onboarding steps to start the session the video stream is blocked and they are not able to proceed with the proctored test.

**Expected behavior**
The test taker should be able to complete the onboarding steps and start their session with a video stream without any interruption in completing the proctored test.

## Steps to reproduce

- Install & configure Proview plugin
- Install & enable Moodle Adaptable theme
- Configure moodle quiz to be proctored
- As a test taker complete the onboarding steps and start the test session. 
- Issue occurs when starting the test session 

## Versions

- Moodle: 3.9 & 4.1
- Browser: NA
- OS: NA

**Comment by rohansharmasitoula** [comment]
## Cause
The Pace Js on the Adaptable theme is currently blocking the WebSocket connection, hindering the video stream connection from streaming.

## Fix

**Step 1:** Navigate to the Appearance Section on Moodle Site Administration
![Step 1](https://github.com/talview/moodle-local_proview/assets/100085662/be793359-cd61-4f72-8ce9-005ec93945f5)

**Step 2:** Click on the Additional HTML option
![Step 2](https://github.com/talview/moodle-local_proview/assets/100085662/fd7d70b6-3fa5-401d-964b-3509ddf17c21)

**Step 3:** Add the following code under the HEAD section of additional HTML.
```javascript
<script>
    var paceOptions = {
        ajax: {
            trackWebSockets: false
        }
    };
</script>
```
![Step 3](https://github.com/talview/moodle-local_proview/assets/100085662/e8e231e8-06db-4125-b03a-130288a53f17)

**Step 4:** : Click on Save Changes

![Step 4](https://github.com/talview/moodle-local_proview/assets/100085662/1308530a-48a2-4ba7-9078-eaf9904f2dfb)
