### ISSUE TITLE
LMS - Playback video is moving up and down in the Quiz page, user is unable to view the playback

### ISSUE THREAD

**Issue by rohansharmasitoula** [talview/moodle-local_proview#84]
LMS - Playback video is moving up and down in the Quiz page, user is unable to view the playback

**Comment by Anil-R07** [comment]
@rohansharmasitoula Tested in Dev env, working as expected 
https://moodle-lms-4-dev.talview.org/moodle/mod/quiz/report.php?id=104&mode=overview
