### ISSUE TITLE
[Firecall] -  Close (X) icon is overriding the candidate id on session id on LMS applications

### ISSUE THREAD

**Issue by Anil-R07** [talview/moodle-local_proview#94]
![Image](https://github.com/user-attachments/assets/cf0dafe8-085d-4803-ab9b-a0f1255fd1bc)

**Comment by SeemaKhan3** [comment]
Validates, Working as expected 

![image](https://github.com/user-attachments/assets/6557b59a-e2d5-40d4-af1e-7cfb1f1033f9)
